ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_i2c_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_torch.o
obj-$(CONFIG_MACH_YULONG) += msm_led_gpio_trigger.o
obj-$(CONFIG_MACH_YULONG) += sgm3780.o
obj-$(CONFIG_MSMB_CAMERA) += lm3642.o
obj-$(CONFIG_MSMB_CAMERA) += sgm3780.o
#begin ljk add for z2
obj-$(CONFIG_MSMB_CAMERA) += ds8540.o
#end
